"""added breed column

Revision ID: 13258235758a
Revises: 
Create Date: 2020-02-15 14:34:37.441914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13258235758a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('breed', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'breed')
    # ### end Alembic commands ###
