"""create table toys

Revision ID: 609e2ecf228a
Revises: 13258235758a
Create Date: 2020-02-15 14:58:18.845214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609e2ecf228a'
down_revision = '13258235758a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toys')
    # ### end Alembic commands ###
